language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
- mvn test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN

notifications:
  # https://docs.travis-ci.com/user/notifications#Notifications
  webhooks:
    urls:
      - "https://bot.proxy.bronies.link/travis/webhook/YVMHr0uSVaigsObgRT7ftHGM48tQkBnZgfCnDdZkHFg"
    on_success: always  # default: always
    on_failure: always  # default: always
    on_start: always    # default: never
    # [always|never|change]  # change means to notify when the build status changes.
