version: '2'
services:
  node:
    build: .
    environment:
      NODE_PORT: 4458
    command: ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"]
    # restart: "unless-stopped"
    # stdin_open: true