version: '2'
services:
  node:
    build: .
    environment:
      NODE_PORT: 4458
    command: ["-agentlib:jdwp=transport=dt_socket,server=n,address=134.169.252.103:5005,suspend=y,onthrow=<FQ exception class name>,onuncaught=<y/n>"]
    # restart: "unless-stopped"
    # stdin_open: true